edition = "2021"
style_edition = "2024"
unstable_features = true

comment_width = 100
fn_params_layout = "Compressed"
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
format_generated_files = false
format_macro_matchers = true
format_strings = true
max_width = 100
merge_derives = false
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
reorder_modules = false
# short_array_element_width_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
